fake_items_db = [
    {
        "id": 1,
        "item": "Canard",
        "brand": "Zenika",
        "color": "red",
        "price": 10,
        "available": True,
    },
    {
        "id": 2,
        "item": "Mug",
        "brand": "Python",
        "color": "yellow and blue",
        "price": 20,
        "available": False,
    },
    {
        "id": 3,
        "item": "T-Shirt",
        "brand": "Java",
        "color": "white",
        "price": 30,
        "available": True,
    },
    {
        "id": 4,
        "item": "Pen",
        "brand": "Enedis",
        "color": "red",
        "price": 5,
        "available": True,
    },
{
        "id": 5,
        "item": "Bag",
        "brand": "Les Plateaux Sauvages",
        "color": "yellow",
        "price": 2,
        "available": True,
    },
{
        "id": 6,
        "item": "Sweat",
        "brand": "Zenika",
        "color": "blue",
        "price": 50,
        "available": False,
    },
{
        "id": 7,
        "item": "Sweat",
        "brand": "Enedis",
        "color": "yellow",
        "price": 30,
        "available": True,
    },
]